ht.insert("key-3", "val-3")
# print(ht)
# ht.insert("key-4", "val-4")
# print(ht)
# ht.insert("key-5", "val-5")
# print(ht)
# ht.insert("key-6", "val-6")
# print(ht)
# ht.insert("key-7", "val-7")
# print(ht)
# ht.insert("key-8", "val-8")
# print(ht)
# ht.insert("key-9", "val-9")
# print(ht)
